name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build docker image
      run: |
        cd test
        docker build -t testimage .

    - name: Run docker container in the background
      run : |
        docker run --name testcontainer -d -p 5000:5000 -v $(pwd):/src/ testimage
        docker exec testcontainer /test/test_wrapper.sh

    - name: Test scripts
      run : |
        docker exec -w /src testcontainer go test -v ./...

    - name: Build
      run: go build -v ./...
